### ISSUE TITLE
the latest commit breaks hosts with custom kernels

### ISSUE THREAD

**Issue by aine-etke** [algodelinux/purge-old-kernels#2]
The https://github.com/algodelinux/purge-old-kernels/commit/ec84027befc1b4c5561b00460fc24153d50150bb breaks systems with `-aws`, `-oracle`, etc. kernels.

Please, hide the `rm` commands under a cli arg (actual file modifications should be handled by corresponding tools, like apt-get and/or enabled manually by providing a special flag).

**Comment by algodelinux** [comment]
I will check the problem for you. I wrote this version to solve problems in our systems and we didn't have -aws or -oracle kernels. Removing files with rm was needed because there were lots of modules directories in /lib/modules and there was no package to uninstall to remove them. The problem could not be solved as you say.

**Comment by aine-etke** [comment]
Here is what we found (mitigations section): https://gitlab.com/etke.cc/website/-/wikis/system/kernel

**Comment by algodelinux** [comment]
Test new version.

**Comment by aine-etke** [comment]
Thanks! Unfortunately, it doesn't address the main problem.

From the wiki page I linked:

```
Modules disappearing seems to be a problem with cloud-initramfs-copymods. This is something which mounts modules found in the initramfs image into /lib/modules. Also reported here:

* https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg6013218.html
* https://unix.stackexchange.com/questions/405146/removed-lib-modules-folder-after-every-reboot

To see if copymods is to blame, try mount | grep /lib/modules. If it says something like copymods on /lib/modules type tmpfs (rw,relatime), then you're not dealing with a real /lib/modules directory, but with a temporary filesystem. Reinstalling modules into that directory will likely not result in them staying after a reboot.
```

So, the actual "fix" on the purge-old-kernels side is to provide a cli arg to enable/disable actual removal of the /lib/modules contents

**Comment by aine-etke** [comment]
Just to clarify: I don't ask you to remove the `rm` commands, I ask you to add a cli arg, eg `--rm-modules=1` or `--no-rm-modules` to enable/disable the `rm` commands

**Comment by algodelinux** [comment]
I understand.

**Comment by algodelinux** [comment]
I note your request in my task list. By now, this change is not necessary for me and I have another priorities. But you can do a fork and make the changes yourself.

**Comment by aine-etke** [comment]
Thank you!

Already did, but in my fork I completely removed the `rm` commands.

Please, leave the issue open, hope you will have a chance to add requested changes some day

**Comment by aine-etke** [comment]
Hi there,
I tried to test the latest commit you pushed, but `$APT_OPTS` parsing fails:

```bash
# purge-old-kernels -n -k 1 -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew
purge-old-kernels: invalid option -- 'y'
purge-old-kernels: invalid option -- 'o'
purge-old-kernels: invalid option -- 'o'
Terminating...

# purge-old-kernels -n -k 1 -- -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew
# ... $APT_OPTS is empty
```

**Comment by algodelinux** [comment]
I didn't include -y or -o options. You can include inside purge-old-kernels in APT_OPTS var.

**Comment by aine-etke** [comment]
Thank you!
